backend:
  name: github
  repo: ds1/ds1.github.io
  branch: main

# Media files storage
media_folder: "src/images"
public_folder: "/images"

# Optional: Enable editorial workflow for drafts
# publish_mode: editorial_workflow

# Content Collections
collections:
  # Case Studies with Flexible Content Blocks
  - name: "case_studies"
    label: "Case Studies"
    folder: "content/cms/case-studies"
    format: "json"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} - {{description}}"
    fields:
      # Basic Metadata (all optional except ID and title)
      - {label: "ID", name: "id", widget: "number", hint: "Unique identifier for ordering"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false, hint: "Short description for the card"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {
          label: "Thumbnail Type", 
          name: "thumbnail_type", 
          widget: "select", 
          options: ["image", "gif", "video"],
          default: "image",
          required: false
        }
      - {label: "Duration", name: "duration", widget: "string", required: false, hint: "e.g., '06/2022 - 08/2024' or 'July 2024'"}
      - {label: "Role", name: "role", widget: "string", required: false}
      - {label: "Project Type", name: "project_type", widget: "string", required: false, hint: "e.g., 'Personal Project', 'Enterprise Tool'"}
      
      # Flexible Content Blocks
      - label: "Content Sections"
        name: "content_blocks"
        widget: "list"
        required: false
        types:
          - label: "Heading 1 (H1)"
            name: "h1"
            widget: "object"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              
          - label: "Heading 2 (H2)"
            name: "h2"
            widget: "object"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              
          - label: "Heading 3 (H3)"
            name: "h3"
            widget: "object"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              
          - label: "Paragraph"
            name: "paragraph"
            widget: "object"
            fields:
              - {label: "Text", name: "text", widget: "text"}
              
          - label: "Rich Text"
            name: "body"
            widget: "object"
            fields:
              - {label: "Content", name: "content", widget: "markdown", hint: "Supports **bold**, *italic*, line breaks, and color spans"}
              
          - label: "List"
            name: "list"
            widget: "object"
            fields:
              - {label: "Items", name: "items", widget: "list", hint: "Add list items one by one"}
              
          - label: "Image"
            name: "image"
            widget: "object"
            fields:
              - {label: "Image File", name: "url", widget: "image"}
              - {label: "Alt Text", name: "alt", widget: "string", required: false}
              - {label: "Caption", name: "caption", widget: "string", required: false}
              
          - label: "Video"
            name: "video"
            widget: "object"
            fields:
              - {label: "Video File", name: "url", widget: "file"}
              - {label: "Alt Text", name: "alt", widget: "string", required: false}
              - {label: "Caption", name: "caption", widget: "string", required: false}
              
          - label: "GIF"
            name: "gif"
            widget: "object"
            fields:
              - {label: "GIF File", name: "url", widget: "image"}
              - {label: "Alt Text", name: "alt", widget: "string", required: false}
              - {label: "Caption", name: "caption", widget: "string", required: false}
              
          - label: "Code Block"
            name: "code"
            widget: "object"
            fields:
              - {label: "Language", name: "language", widget: "string", default: "javascript"}
              - {label: "Code", name: "code", widget: "code"}
              
          - label: "Quote"
            name: "quote"
            widget: "object"
            fields:
              - {label: "Quote Text", name: "text", widget: "text"}
              - {label: "Author", name: "author", widget: "string", required: false}
              
          - label: "Divider"
            name: "divider"
            widget: "object"
            fields:
              - {label: "Style", name: "style", widget: "hidden", default: "---"}
      
      # Tags Section (all optional)
      - label: "Tags"
        name: "tags"
        widget: "object"
        collapsed: true
        required: false
        fields:
          - {label: "Design Tools", name: "design_tools", widget: "list", required: false, hint: "e.g., Figma, Sketch, Adobe XD"}
          - {label: "AI Tools", name: "ai_tools", widget: "list", required: false, hint: "e.g., Claude, ChatGPT, Midjourney"}
          - {label: "Dev Tools", name: "dev_tools", widget: "list", required: false, hint: "e.g., React, TypeScript, GitHub"}
          - {label: "Skills", name: "skills", widget: "list", required: false, hint: "e.g., UX Research, Prototyping"}
          - {label: "Roles", name: "roles", widget: "list", required: false, hint: "e.g., Lead Designer, Product Manager"}
          - {label: "Artifact Types", name: "artifact_types", widget: "list", required: false}
          - {label: "Fidelity", name: "fidelity", widget: "list", required: false, hint: "e.g., Low, Medium, High"}
          - {label: "AI Models", name: "ai_models", widget: "list", required: false}
          - {label: "Design Principles", name: "design_principles", widget: "list", required: false}
          - {label: "Usability Heuristics", name: "usability_heuristics", widget: "list", required: false}

  # Other pages
  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "content/cms/about.json"
        fields:
          - {label: "Headline", name: "headline", widget: "string"}
          - {label: "Introduction", name: "introduction", widget: "text"}
          - {label: "Profile Image", name: "profileImage", widget: "image"}
          - {label: "Facts", name: "facts", widget: "list"}
          - label: "Content Sections"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Content", name: "content", widget: "markdown"}
      
      - name: "resume"
        label: "Resume Page"
        file: "content/cms/resume.json"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Introduction", name: "introduction", widget: "text"}
          - {label: "Download Link", name: "downloadLink", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}
      
      - name: "contact"
        label: "Contact Page"
        file: "content/cms/contact.json"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Introduction", name: "introduction", widget: "text"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "LinkedIn", name: "linkedin", widget: "string"}
          - {label: "GitHub", name: "github", widget: "string"}
          - {label: "Message", name: "message", widget: "text"}