backend:
  name: github
  repo: ds1/ds1.github.io
  branch: main

# Media files storage
media_folder: "src/images"
public_folder: "/images"

# Content Collections
collections:
  # Case Studies with Flexible Content
  - name: "case_studies"
    label: "Case Studies"
    folder: "content/cms/case-studies"
    format: "json"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} - {{description}}"
    fields:
      # Basic Metadata
      - {label: "ID", name: "id", widget: "number", hint: "Unique identifier for ordering"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false, hint: "Short description for the card"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {
          label: "Thumbnail Type", 
          name: "thumbnail_type", 
          widget: "select", 
          options: ["image", "gif", "video"],
          default: "image",
          required: false
        }
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Role", name: "role", widget: "string", required: false}
      - {label: "Project Type", name: "project_type", widget: "string", required: false}
      
      # Flexible Content Sections - Using simple list of markdown blocks
      - label: "Content Sections"
        name: "content_sections"
        widget: "list"
        required: false
        fields:
          - label: "Section Type"
            name: "type"
            widget: "select"
            options: 
              - { label: "Heading 1", value: "h1" }
              - { label: "Heading 2", value: "h2" }
              - { label: "Heading 3", value: "h3" }
              - { label: "Paragraph", value: "paragraph" }
              - { label: "Rich Text", value: "body" }
              - { label: "List", value: "list" }
              - { label: "Image", value: "image" }
              - { label: "Video", value: "video" }
              - { label: "Code", value: "code" }
              - { label: "Quote", value: "quote" }
          
          - {label: "Content", name: "content", widget: "text", required: false, hint: "Main content for this section. For lists, use semicolons to separate items"}
          - {label: "List Items (deprecated - use Content field)", name: "items", widget: "text", required: false, hint: "Legacy field - please use Content field above"}
          - {label: "Image/Video URL", name: "media_url", widget: "image", required: false}
          - {label: "Alt Text", name: "alt", widget: "string", required: false}
          - {label: "Caption", name: "caption", widget: "string", required: false}
          - {label: "Code Language", name: "language", widget: "string", required: false, default: "javascript"}
      
      # Media Gallery (optional, simpler approach)
      - label: "Media Gallery"
        name: "media"
        widget: "list"
        required: false
        fields:
          - {label: "Media Type", name: "type", widget: "select", options: ["image", "gif", "video"], default: "image"}
          - {label: "File", name: "url", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string", required: false}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      
      # Tags Section (all optional)
      - {label: "Design Tools", name: "design_tools", widget: "text", required: false, hint: "Semicolon-separated list"}
      - {label: "AI Tools", name: "ai_tools", widget: "text", required: false, hint: "Semicolon-separated list"}
      - {label: "Dev Tools", name: "dev_tools", widget: "text", required: false, hint: "Semicolon-separated list"}
      - {label: "Skills", name: "skills", widget: "text", required: false, hint: "Semicolon-separated list"}
      - {label: "Roles", name: "roles", widget: "text", required: false, hint: "Semicolon-separated list"}
      - {label: "Artifact Types", name: "artifact_types", widget: "text", required: false, hint: "Semicolon-separated list"}
      - {label: "Fidelity", name: "fidelity", widget: "text", required: false, hint: "Semicolon-separated list"}
      - {label: "AI Models", name: "ai_models", widget: "text", required: false, hint: "Semicolon-separated list"}

  # Static Pages
  - name: "site_pages"
    label: "Site Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "content/cms/about.json"
        fields:
          - {label: "Headline", name: "headline", widget: "string"}
          - {label: "Introduction", name: "introduction", widget: "text"}
          - {label: "Profile Image", name: "profileImage", widget: "image"}
          - {label: "Facts", name: "facts", widget: "list"}
      
      - name: "resume"
        label: "Resume Page"
        file: "content/cms/resume.json"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Introduction", name: "introduction", widget: "text"}
          - {label: "Download Link", name: "downloadLink", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}
      
      - name: "contact"
        label: "Contact Page"
        file: "content/cms/contact.json"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Introduction", name: "introduction", widget: "text"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "LinkedIn", name: "linkedin", widget: "string"}
          - {label: "GitHub", name: "github", widget: "string", required: false}
          - {label: "Message", name: "message", widget: "text"}