backend:
  name: github
  repo: ds1/ds1.github.io
  branch: main

# Enable preview
editor:
  preview: true  # Make sure preview is enabled

# Media files storage
media_folder: "src/images"
public_folder: "/images"

# Content Collections
collections:
  # Simplified Case Studies
  - name: "case_studies"
    label: "Case Studies"
    folder: "content/cms/case-studies"
    format: "json"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}}"
    fields:
      # Basic Info
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Role", name: "role", widget: "string", required: false}
      - {label: "Project Type", name: "project_type", widget: "string", required: false}
      
      # Main Content Fields
      - {label: "Initial Vision", name: "initial_vision_h1", widget: "string", required: false}
      - {label: "Problem Statement Title", name: "problem_statement_h2", widget: "string", required: false}
      - {label: "Problem Body", name: "problem_body", widget: "markdown", required: false}
      - {label: "Technical Approach Title", name: "technical_approach_h2", widget: "string", required: false}
      - {label: "Approach List", name: "approach_list", widget: "text", required: false, hint: "Separate items with semicolons"}
      - {label: "Architecture Title", name: "architecture_h2", widget: "string", required: false}
      - {label: "Architecture Body", name: "architecture_body", widget: "markdown", required: false}
      - {label: "Innovation Title", name: "innovation_details_h2", widget: "string", required: false}
      - {label: "Innovation Body", name: "innovation_body", widget: "markdown", required: false}
      - {label: "Collaboration Title", name: "collaboration_h2", widget: "string", required: false}
      - {label: "Collaboration Body", name: "collaboration_body", widget: "markdown", required: false}
      - {label: "Results Title", name: "results_h2", widget: "string", required: false}
      - {label: "Results List", name: "results_list", widget: "text", required: false, hint: "Separate items with semicolons"}
      
      # Tags (simplified)
      - {label: "Design Tools", name: "design_tools", widget: "text", required: false, hint: "Semicolon-separated"}
      - {label: "AI Tools", name: "ai_tools", widget: "text", required: false, hint: "Semicolon-separated"}
      - {label: "Dev Tools", name: "dev_tools", widget: "text", required: false, hint: "Semicolon-separated"}
      - {label: "Skills", name: "skills", widget: "text", required: false, hint: "Semicolon-separated"}
      - {label: "Roles", name: "roles", widget: "text", required: false, hint: "Semicolon-separated"}

  # Static Pages
  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "content/cms/about.json"
        fields:
          - {label: "Headline", name: "headline", widget: "string"}
          - {label: "Introduction", name: "introduction", widget: "text"}
          - {label: "Profile Image", name: "profileImage", widget: "image"}
          - {label: "Facts", name: "facts", widget: "list"}
      
      - name: "resume"
        label: "Resume Page"
        file: "content/cms/resume.json"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Introduction", name: "introduction", widget: "text"}
          - {label: "Download Link", name: "downloadLink", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}
      
      - name: "contact"
        label: "Contact Page"
        file: "content/cms/contact.json"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Introduction", name: "introduction", widget: "text"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "LinkedIn", name: "linkedin", widget: "string"}
          - {label: "GitHub", name: "github", widget: "string", required: false}
          - {label: "Message", name: "message", widget: "text"}