name: Build and Deploy

on:
  push:
    branches: [ main ]
    # Triggers on any push to main branch

# Add permissions for the workflow
permissions:
  contents: write  # This gives write access to the repository
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Convert content
      run: |
        npm run convert-content
        echo "Content converted successfully"
        
    - name: Build project
      run: |
        npm run build
        echo "Build completed"
        
    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/
        git add src/data/
        git diff --staged --quiet || git commit -m "Auto-build from CMS changes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}